### ISSUE TITLE
Linked events is not Django REST framework 3.0 compatible

### ISSUE THREAD

**Issue by aapris** [City-of-Helsinki/linkedevents#42]
Linked events is currently not Django REST framework 3.0 compatible. After upgrading DRF from 2.x->3.0.1 attempt to start dev server raises this:

```
$ python manage.py runserver
Validating models...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x107d4e488>
Traceback (most recent call last):
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/urlresolvers.py", line 358, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/utils/autoreload.py", line 93, in wrapper
    fn(*args, **kwargs)
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 102, in inner_run
    self.validate(display_num_errors=True)
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File ".../virtualenv/linkedevents3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/debug_toolbar/models.py", line 9, in <module>
    dt_settings.patch_all()
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/debug_toolbar/settings.py", line 215, in patch_all
    patch_root_urlconf()
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/debug_toolbar/settings.py", line 203, in patch_root_urlconf
    reverse('djdt:render_panel')
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/urlresolvers.py", line 507, in reverse
    app_list = resolver.app_dict[ns]
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/urlresolvers.py", line 267, in _populate
    for pattern in reversed(self.url_patterns):
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File ".../virtualenv/linkedevents3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File ".../linkedevents/demoform/urls.py", line 11, in <module>
    from linkedevents.urls import urlpatterns as urlpatterns2
  File ".../linkedevents/linkedevents/urls.py", line 8, in <module>
    url(r'^v0.1/', include('events.urls')),
  File ".../virtualenv/linkedevents3/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File ".../virtualenv/linkedevents3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File ".../linkedevents/events/urls.py", line 3, in <module>
    from events import api
  File ".../linkedevents/events/api.py", line 108, in <module>
    class EnumChoiceField(serializers.WritableField):
AttributeError: 'module' object has no attribute 'WritableField'
```
See http://www.django-rest-framework.org/api-guide/fields/#custom-fields
"Note that the WritableField class that was present in version 2.x no longer exists. You should subclass Field and override to_internal_value() if the field supports data input."

**Comment by aapris** [comment]
How to (hopefully) make Linked events, Django 1.7 and Django Rest Framework 3.0 work. Following diffs are from `events/api.py`.

`events.api.SearchViewSet` fails in this. `hasattr(klass.serializer_class, 'Meta')` seems to be a solution.

```
45c45
<     if klass.serializer_class and hasattr(klass.serializer_class, 'Meta') and hasattr(klass.serializer_class.Meta, 'model'):
---
>     if klass.serializer_class and hasattr(klass.serializer_class.Meta, 'model'):
```

**Comment by aapris** [comment]
- `WritableField` doesn't exist anymore, `Field` is used instead.
 - `to_internal_value` has been renamed to `to_native`
 - 
```
108c108
< class EnumChoiceField(serializers.Field):
---
> class EnumChoiceField(serializers.WritableField):
122c122
<     def to_internal_value(self, obj):
---
>     def to_native(self, obj):
128c128
<     def to_representation(self, data):
---
>     def from_native(self, data):
133d131
< class ISO8601DurationField(serializers.Field):
135c133,134
<     def to_internal_value(self, obj):
---
> class ISO8601DurationField(serializers.WritableField):
>     def to_native(self, obj):
142c141
<     def to_representation(self, data):
---
>     def from_native(self, data):
```

**Comment by aapris** [comment]
For some reason `data` must be a str.

```
130,131c130
<                                                self.prefix + str(data), 0)
< 
---
>                                                self.prefix + data, 0)
```

**Comment by aapris** [comment]
`self.opts.model` doesn't exist anymore, but `self.Meta.model` seems to be available.

165c164
<         model = self.Meta.model
---
>         model = self.opts.model

**Comment by aapris** [comment]
Many positional has disappeared from BaseSerializer.__init__ in rest_framework.serializers.
```
246c245,247
<         super(LinkedEventsSerializer, self).__init__(instance, data,
---
>         super(LinkedEventsSerializer, self).__init__(instance, data, files,
>                                                      context, partial, many,
>                                                      allow_add_remove,
```

**Comment by aapris** [comment]
Explicit queryset required on relational fields. "Relationships must either set a queryset explicitly, or set read_only=True":
http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedrelatedfield
I'm not sure which one is correct in this case. Probably, if you want to save Events through API some day, read_only=True is not an option?

```
439c440
<     location = JSONLDRelatedField(serializer=PlaceSerializer, required=False, queryset=Place.geo_objects.all(),
---
>     location = JSONLDRelatedField(serializer=PlaceSerializer, required=False,
442c443
<     keywords = JSONLDRelatedField(serializer=KeywordSerializer, many=True, required=False, queryset=Keyword.objects.all(),
---
>     keywords = JSONLDRelatedField(serializer=KeywordSerializer, many=True, required=False,
444c445
<     super_event = JSONLDRelatedField(required=False, view_name='event-detail', queryset=Event.objects.all())
---
>     super_event = JSONLDRelatedField(required=False, view_name='event-detail')
449c450
<                                     required=False, view_name='event-detail', many=True, queryset=[])
---
>                                     required=False, view_name='event-detail', many=True)
```
